### ISSUE TITLE
Support host mounts in containers

### ISSUE THREAD

**Issue by kegsay** [matrix-org/complement#233]
Developers often want to run new tests against a _local_ version of their HS. This is cumbersome at present as you have to rebuild a docker image before you can run the test. Instead, we can expose directory on the container which will be volume mounted from a new env var e.g:
```
COMPLEMENT_MOUNT=/Users/me/my/local/dendrite
COMPLEMENT_BASE_IMAGE=dendrite-which-reads-mounted-dir:latest
go test ./...
```
- Should we just expose the source location or also the destination location e.g `COMPLEMENT_MOUNT=/Users/me/my/local/dendrite:/data`
- We should standardise the mounted directories (as `/ca` is done for `COMPLEMENT_CA=1`) as we will inevitably expand this in the future (e.g appservices need registration YAML files in the container)

We can either be prescriptive and say that we map to a static directory layout:
```
/complement
    |__ /appservice
    |__ /ca
    |__ /mount
```
or we can make this configurable e.g:
```
COMPLEMENT_MOUNT=/Users/me/my/local/dendrite:/mnt
COMPLEMENT_CA=/Users/me/my/ca:/certs
COMPLEMENT_AS=/Users/me/my/appservices:/as
```
This feels wrong though as it then ties env vars to a specific docker image which isn't what we're trying to do here (we want them to be interchangeable), so let's be prescriptive.

**Comment by ShadowJonathan** [comment]
I think these mounts should be read-only, considering that Complement isn't supposed to do more than just read their code.

Any write-specific issues and behaviour can be fixed by layering a copy-on-write layer on top of it (though i can't remember exactly how or if thats possible with docker)

---

Regarding mapping; i think that complement should document well-known locations (`/mnt/`, `/certs`, and `/as` in that example) within its container, and then have the developer submit a `;`-seperated mount list to the runner.
