### ISSUE TITLE
Unexplained failure (flake?) in TestFetchHistoricalJoinedEventDenied

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/complement#291]
[This synapse CI run](https://github.com/matrix-org/synapse/runs/4938840206?check_suite_focus=true#step:8:714) failed its complement step:

```
❌ TestFetchHistoricalJoinedEventDenied (3.12s)
      apidoc_room_history_visibility_test.go:86: Deploy times: 8.596861ms blueprints, 2.906504072s containers
      client.go:490: POST hs1/_matrix/client/r0/createRoom => 401 Unauthorized (6.765927ms)
      apidoc_room_history_visibility_test.go:23: CSAPI.MustDo POST http://localhost:49237/_matrix/client/r0/createRoom returned HTTP 401
  2022/01/25 15:15:13 ============================================
  
  
  2022/01/25 15:15:13 47530ed878655a1e50112a0c67b2c672848fc91e76cfe3cd99a811c04996c368 : Server logs:
  Signature ok
  subject=CN = hs1
  Getting CA Private Key
  2022/01/25 15:15:13 ============== 47530ed878655a1e50112a0c67b2c672848fc91e76cfe3cd99a811c04996c368 : END LOGS ==============
```

rerunning the job, it [succeeded](https://github.com/matrix-org/synapse/runs/4939376425?check_suite_focus=true).

Unclear if complement is at fault or the test.

**Comment by ShadowJonathan** [comment]
I have a suspicion this is synapse reporting readiness before being able to actually receive room creation calls like this, though I might be wrong.

Multiple similar versions of this test exists, and all of these create rooms directly at the start, so if this is a legitimate test flake, i think we'd be seeing a lot more of it.

Regardless, thanks for filing.

**Comment by kegsay** [comment]
It's the first instruction issued to Synapse, and in the failed test Synapse returns a 401 to `/createRoom` but 200 OK in the passing test. This doesn't feel like a Complement issue. There's nothing here that can race. If, however:

> synapse reporting readiness before being able to actually receive room creation calls like this

Then yes, that would be a race and is something which needs to be fixed in the Synapse dockerfile. In practice this means that `/versions` will 200 OK but `/createRoom` will 401.

We're now logging the HTTP response body for this call in https://github.com/matrix-org/complement/commit/8b4724be6ba0551d5e43b6ef0dd2de3548ef5414 which should help elucidate things.

**Comment by DMRobertson** [comment]
Thanks both. that sounds much more plausible. Let's close this for now; I'll keep an eye on on synapse CI runs.
