### ISSUE TITLE
Synapse will not pass TestKeysQueryWithDeviceIDAsObjectFails due to backwards-compatibility handling

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/complement#50]
`TestKeysQueryWithDeviceIDAsObjectFails` checks that non-spec compliant behaviour does not occur. This behaviour was specifically being exhibited by Element iOS ([issue](https://github.com/vector-im/element-ios/issues/3539)). Synapse will likely maintain backwards compatibility here for the long line of old Element iOS clients, and thus Synapse is unlikely to pass this test any time soon.

We'd like to get Synapse passing all of a subset of tests in order to have Complement not soft-fail in our CI. Perhaps one solution is to add a build tag for backwards-compatibility checks such as this one, which Synapse can disable?

**Comment by richvdh** [comment]
it doesn't really feel like it's Complement's job to check how the server handles non-spec-compliant clients?

**Comment by Kegsay** [comment]
Complement should be allowed to do negative testing e.g "I do X, I expect it to fail". There's never been any indication in the spec or otherwise that this specific endpoint accepts a map, and when I looked at the code it just seemed like a classic thinko of not validating the type before looping over it and python has the same syntax for looping over maps and arrays.

This _was_ a bug for Dendrite because it meant iOS devices didn't work.

**Comment by richvdh** [comment]
> There's never been any indication in the spec or otherwise that this specific endpoint accepts a map,

right, but there has also never been any indication in the spec or otherwise that sending a map to that endpoint should fail in any specific way. Who is to say that Complement's expectation is any more valid than Synapse's?

> This was a bug for Dendrite because it meant iOS devices didn't work.

it sounds like it was a bug in Element iOS, not Dendrite, to me.

**Comment by anoadragon453** [comment]
FTR the iOS bug has now been fixed: https://github.com/vector-im/element-ios/issues/3539

**Comment by anoadragon453** [comment]
> This *was* a bug for Dendrite because it meant iOS devices didn't work.

> it sounds like it was a bug in Element iOS, not Dendrite, to me.

Either way, sounds like it belongs in a unit tests rather than Complement?

**Comment by anoadragon453** [comment]
@richvdh @Kegsay I'd like to get this resolved sometime this week so I can put Complement onto Synapse's CI without needing to soft-fail it.

I like to think of this from the opposite perspective to mine. If some homeserver started running Sytest and it turns out that it was accidentally doing the wrong thing for a while, and thus required myself or someone else to update Sytest (even though it was running against Synapse perfectly fine before). I probably wouldn't be too impressed. Switching that Sytest to a Synapse unit test is one solution but feels a bit dirty, as now all homeservers other than the affected one need to do so to maintain test coverage.

A different solution for this is for the affected homeserver to blacklist that test until enough time has passed before it can remove the offending backwards compatibility. In this case in Synapse, we probably won't do that for... quite some time. But that's OK, we can write other, spec-compliant tests if we feel that we're lacking testing on that endpoint.

At the moment blacklisting and whitelisting tests is done in Complement itself via [build tags](https://golang.org/cmd/go/#hdr-Build_constraints), which homeservers can choose to enable or disable. This is the path I'm currently leaning towards. 

Does that sound reasonable?

**Comment by richvdh** [comment]
I've had a look at the test in question (here: https://github.com/matrix-org/complement/blob/a843aa9faba5f8b6a90804a36fb7516ca9749c8e/tests/user_query_keys_test.go#L16). There are some subtleties that weren't particularly clear from the original description - in particular, it's not really testing behaviour that's outside the spec. It's entirely reasonable to expect a HS impl to return a 400 if you send a dict where the spec mandates an array.

Accordingly, I think the best way forward here is indeed to blacklist this test for Synapse for now, but I'd also like us to decide a time in the future where we will no longer support the incorrect behaviour and set some sort of reminder for ourselves (or even a timebomb...)

**Comment by Kegsay** [comment]
> At the moment blacklisting and whitelisting tests is done in Complement itself via build tags, which homeservers can choose to enable or disable. This is the path I'm currently leaning towards.

Build tags are inclusive and not exclusive, so you can't say things like `go test --tags=not-these-tests` you can only say `go test --tags=these-tests`. However, you can (ab)use the build tag comment itself to invert the rule e.g `// +build !these-tests`

It is desirable for a native "no tag" run to run all the spec compliance tests so new servers don't need to add an incantation of tags to their `go test`. Given this, you should be able to:
 - Define `synapse-blacklist` as a tag
 - Add `// +build !synapse-blacklist` to all files which contain tests which should be blacklisted by synapse.
 - Normal "no tag" runs will run all the tests (because the `!` in the build tag means the empty set of tags passes the rule).
 - Runs with `--tags=synapse-blacklist` will skip the files with `// +build !synapse-blacklist`, producing the behaviour we desire.

It's a little wonky, but should work as we want it to.

**Comment by anoadragon453** [comment]
That sounds workable! @richvdh does that work for you? I'll work under the assumption that this is how we're going to do it over the next few days.

**Comment by richvdh** [comment]
sure, sounds good to me.

(sounds like this system won't scale well if you want a given test to end up on two or more blacklists?)

**Comment by anoadragon453** [comment]
@richvdh You can apply multiple tags to a single file and use commas and spaces to apply boolean logic. For instance, if I had a test that was blacklisted by Synapse and Conduit, I'd write:

```
// +build: !synapse-blacklist,!conduit-blacklist
```

which evaluates to `(NOT synapse-blacklist) AND (NOT conduit-blacklist)`. More info available at: https://golang.org/cmd/go/#hdr-Build_constraints

**Comment by anoadragon453** [comment]
Blacklist tag implemented in #55.
