### ISSUE TITLE
`should` counterpart to `must`

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/complement#546]
This came up while thinking of a solution for [this comment](https://github.com/matrix-org/complement/pull/535#discussion_r1009458884), I think it would help if we have a `should` package that mirrors the current `must` package, but omit the `*testing.T` input, and instead have an `error` output.

This'd allow to use the matching inside `client.SyncCheckOpt`, JSONCheckOff (and friends) and other such conditions, where tentative checking ("should match") needs to be done instead of harsh ("must match") checking.

Code between the modules dont need to be duplicated, as `must` code can become `should` code, with returning the error instead of `t.Fatalf`-ing it, and `must` only taking functions from `should` and aborting on failure when its non-nil.

**Comment by kegsay** [comment]
This has come up a few times. See https://github.com/matrix-org/complement/pull/521#discussion_r997228161

The matchers themselves are doing the right thing and return `error` types. The problem is that they are typically paired with `must` functions, which as the package suggests, is fatal if there's a problem. It may be enough to just do as you describe:
 - remove t.Fatal/Error on existing `must` functions
 - rename package to `should`
 - add new `must` package which just proxies to `should` and fails if there is an error.
